name: Manual Publish to NPM

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag/version to publish (e.g., v1.0.0)'
        required: true
        default: 'latest'
      dry_run:
        description: 'Dry run (no actual publish)'
        required: false
        default: false
        type: boolean

permissions:
  contents: read
  packages: write

jobs:
  manual-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag == 'latest' && 'main' || github.event.inputs.tag }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm test
      
      - name: Build
        run: npm run build
      
      - name: Display package info
        run: |
          echo "Package name: $(node -p "require('./package.json').name")"
          echo "Package version: $(node -p "require('./package.json').version")"
          echo "Publishing tag: ${{ github.event.inputs.tag }}"
          echo "Dry run: ${{ github.event.inputs.dry_run }}"
      
      - name: Publish to NPM (Dry Run)
        if: ${{ github.event.inputs.dry_run == true }}
        run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Publish to NPM
        if: ${{ github.event.inputs.dry_run != true }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 