name: Manual Publish to NPM

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag/version to publish (e.g., v1.0.0)'
        required: true
        default: 'latest'
      dry_run:
        description: 'Dry run (no actual publish)'
        required: false
        default: false
        type: boolean
      access:
        description: 'Package access (public or restricted)'
        required: false
        default: 'public'
        type: string

permissions:
  contents: read
  packages: write

jobs:
  manual-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag == 'latest' && 'main' || github.event.inputs.tag }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Run npm pkg fix
        run: npm pkg fix
      
      - name: Run tests
        run: npm test
      
      - name: Build
        run: npm run build
      
      - name: Display package info
        run: |
          echo "Package name: $(node -p "require('./package.json').name")"
          echo "Package version: $(node -p "require('./package.json').version")"
          echo "Publishing tag: ${{ github.event.inputs.tag }}"
          echo "Access level: ${{ github.event.inputs.access }}"
          echo "Dry run: ${{ github.event.inputs.dry_run }}"
          echo "NPM_TOKEN defined: ${{ secrets.NPM_TOKEN != '' }}"
      
      - name: Verify NPM token
        run: |
          if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
            echo "::error::NPM_TOKEN secret is not set! You need to add it in the repository secrets."
            exit 1
          fi
          
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          npm whoami || {
            echo "::error::NPM token is invalid or does not have publish permissions."
            echo "Please check that your NPM_TOKEN:"
            echo "1. Is valid and not expired"
            echo "2. Has publish access to the package namespace"
            echo "3. If this is a scoped package, make sure the token has access to the scope"
            exit 1
          }
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Publish to NPM (Dry Run)
        if: ${{ github.event.inputs.dry_run == true }}
        run: npm publish --dry-run --access ${{ github.event.inputs.access }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Publish to NPM
        if: ${{ github.event.inputs.dry_run != true }}
        run: npm publish --access ${{ github.event.inputs.access }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 